// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjx-WgNBKiGJfEbG1rxmtpEA8ULQOVDys',
    appId: '1:862823942685:web:a04785a8a0c59542a6d4f4',
    messagingSenderId: '862823942685',
    projectId: 'appiot-da23c',
    authDomain: 'appiot-da23c.firebaseapp.com',
    databaseURL: 'https://appiot-da23c-default-rtdb.firebaseio.com',
    storageBucket: 'appiot-da23c.appspot.com',
    measurementId: 'G-M0K7VFCSWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDquZb8B0iEuypMauAvbP2z5uQHXUjfiq8',
    appId: '1:862823942685:android:b11d84681b10c9bea6d4f4',
    messagingSenderId: '862823942685',
    projectId: 'appiot-da23c',
    databaseURL: 'https://appiot-da23c-default-rtdb.firebaseio.com',
    storageBucket: 'appiot-da23c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkR0MdCl-kZrjDW7h83pALlUvB7tN0gD0',
    appId: '1:862823942685:ios:fa79a90a02ce0e80a6d4f4',
    messagingSenderId: '862823942685',
    projectId: 'appiot-da23c',
    databaseURL: 'https://appiot-da23c-default-rtdb.firebaseio.com',
    storageBucket: 'appiot-da23c.appspot.com',
    iosBundleId: 'com.example.appiot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkR0MdCl-kZrjDW7h83pALlUvB7tN0gD0',
    appId: '1:862823942685:ios:a74f463fcf697c90a6d4f4',
    messagingSenderId: '862823942685',
    projectId: 'appiot-da23c',
    databaseURL: 'https://appiot-da23c-default-rtdb.firebaseio.com',
    storageBucket: 'appiot-da23c.appspot.com',
    iosBundleId: 'com.example.appiot.RunnerTests',
  );
}
